### ISSUE TITLE
Navbar not colored correctly on some devices

### ISSUE THREAD

**Issue by fischer-felix** [quillpad/quillpad#15]
On some devices (including my LG V30, Android 9), the navbar does not get themed by `themes.xml`.
This can be worked around by programmatically setting the colour of the navbar.
(the navigation buttons are well visible on white in real live, they only fade a bit after a while of not touching the display in order to prevent burn-in)

without workaround | with workaround
----------------------------|-----------------------
Gray | 
![Screenshot_20221118-225413](https://user-images.githubusercontent.com/65448408/202810676-e6cde962-6e02-4be6-a96a-7a28b429c1c9.png) | ![Screenshot_20221118-225653](https://user-images.githubusercontent.com/65448408/202810787-db3c93b6-5f82-4665-b6c3-bbb49d20a5e6.png)
![Screenshot_20221118-225534](https://user-images.githubusercontent.com/65448408/202810694-2ad9a50b-44d5-4677-8879-010ecd94c5c4.png) | ![Screenshot_20221118-225657](https://user-images.githubusercontent.com/65448408/202810790-26096071-ec90-41b4-890d-44f6fe293414.png)
Black | 
![Screenshot_20221118-225435](https://user-images.githubusercontent.com/65448408/202810714-b13b3fd5-6727-482a-8659-50e4372ca7c2.png) | ![Screenshot_20221118-225734](https://user-images.githubusercontent.com/65448408/202810812-45bd16cc-4e4e-49af-8b9a-9e2e15ccb0f0.png)
![Screenshot_20221118-225516](https://user-images.githubusercontent.com/65448408/202810720-5aecf0d0-e889-42f8-bbea-9017083058ce.png) | ![Screenshot_20221118-225739](https://user-images.githubusercontent.com/65448408/202810821-b9dd9c41-40c6-45a5-824e-b85fb3ea5cfd.png)
White | 
![Screenshot_20221118-225446](https://user-images.githubusercontent.com/65448408/202810743-b4877214-3837-4437-a39d-4939615801bc.png) | ![Screenshot_20221118-225713](https://user-images.githubusercontent.com/65448408/202810839-290e886c-9878-4d2c-80c0-5aaaac71d935.png)
![Screenshot_20221118-225506](https://user-images.githubusercontent.com/65448408/202810748-279ac8f4-727e-400d-b341-167fc3764fcf.png) | ![Screenshot_20221118-225722](https://user-images.githubusercontent.com/65448408/202810844-564bc32f-bdb1-45cf-bfa7-444b7dc88df2.png)

Issue for #14

**Comment by jsixface** [comment]
@fischer-felix Is this issue fixed now ?

**Comment by fischer-felix** [comment]
Oh, sorry forgot to close this, yes it is fixed.

**Comment by laraib07** [comment]
@fischer-felix I am on android 13, arrow OS, using gestures. Here the issue still persists. 
![Screenshot_20221205-132832_Quillpad](https://user-images.githubusercontent.com/25507825/205584117-6829e1c5-83cd-4bc3-8d04-e637908b1bbe.png)


Try this guide : https://developer.android.com/develop/ui/views/layout/edge-to-edge

**Comment by fischer-felix** [comment]
thanks for the heads up, will check when I get home
